"""seed crops

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-03-24 00:01:00.000000

"""
from typing import Sequence, Union
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PgEnum, JSONB


revision: str = "b2c3d4e5f6a7"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

now = datetime.now(timezone.utc)

CROPS = [
    # ── Vegetables ────────────────────────────────────────────────────────────
    {
        "id": "c1000000-0000-0000-0000-000000000001",
        "name": "Tomato",
        "latin_name": "Solanum lycopersicum",
        "category": "vegetable",
        "description": "A warm-season staple bearing fleshy, acidic fruit. Requires staking and regular pruning of suckers for best yield.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Tomato",
        "days_to_germination": 7,
        "days_to_harvest": 75,
        "watering_frequency_days": 2,
        "fertilise_frequency_days": 14,
        "prune_frequency_days": 7,
        "prune_start_day": 21,
        "sun_requirement": "full_sun",
        "spacing_cm": 60,
        "soil_mix": {"name": "Tomato Mix", "topsoil_pct": 40, "compost_pct": 40, "perlite_pct": 20, "description": "Rich, well-draining mix that retains moisture while preventing root rot."},
        "companion_crops": ["Basil", "Marigold", "Carrot"],
        "avoid_crops": ["Fennel", "Kale"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000002",
        "name": "Cherry Tomato",
        "latin_name": "Solanum lycopersicum var. cerasiforme",
        "category": "vegetable",
        "description": "Compact tomato producing clusters of small, sweet fruit. More forgiving than beefsteak varieties.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Cherry+Tomato",
        "days_to_germination": 7,
        "days_to_harvest": 60,
        "watering_frequency_days": 2,
        "fertilise_frequency_days": 14,
        "prune_frequency_days": 10,
        "prune_start_day": 21,
        "sun_requirement": "full_sun",
        "spacing_cm": 45,
        "soil_mix": {"name": "Tomato Mix", "topsoil_pct": 40, "compost_pct": 40, "perlite_pct": 20, "description": "Rich, well-draining mix that retains moisture while preventing root rot."},
        "companion_crops": ["Basil", "Parsley"],
        "avoid_crops": ["Fennel"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000003",
        "name": "Courgette",
        "latin_name": "Cucurbita pepo",
        "category": "vegetable",
        "description": "Fast-growing summer squash with high yield. Harvest regularly when small for best flavour and continued production.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Courgette",
        "days_to_germination": 5,
        "days_to_harvest": 55,
        "watering_frequency_days": 2,
        "fertilise_frequency_days": 21,
        "prune_frequency_days": None,
        "prune_start_day": None,
        "sun_requirement": "full_sun",
        "spacing_cm": 90,
        "soil_mix": {"name": "Rich Bed Mix", "topsoil_pct": 50, "compost_pct": 40, "perlite_pct": 10, "description": "Nutrient-dense mix for heavy feeders."},
        "companion_crops": ["Nasturtium", "Corn"],
        "avoid_crops": ["Potato", "Fennel"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000004",
        "name": "Cucumber",
        "latin_name": "Cucumis sativus",
        "category": "vegetable",
        "description": "Vining crop that thrives on a trellis. Needs consistent moisture to prevent bitter fruit.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Cucumber",
        "days_to_germination": 5,
        "days_to_harvest": 60,
        "watering_frequency_days": 1,
        "fertilise_frequency_days": 14,
        "prune_frequency_days": None,
        "prune_start_day": None,
        "sun_requirement": "full_sun",
        "spacing_cm": 30,
        "soil_mix": {"name": "Rich Bed Mix", "topsoil_pct": 50, "compost_pct": 40, "perlite_pct": 10, "description": "Nutrient-dense mix for heavy feeders."},
        "companion_crops": ["Radish", "Sunflower"],
        "avoid_crops": ["Rosemary"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000005",
        "name": "Carrot",
        "latin_name": "Daucus carota",
        "category": "vegetable",
        "description": "Root vegetable requiring deep, loose soil free of stones. Sow direct — does not transplant well.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Carrot",
        "days_to_germination": 14,
        "days_to_harvest": 75,
        "watering_frequency_days": 3,
        "fertilise_frequency_days": 30,
        "prune_frequency_days": None,
        "prune_start_day": None,
        "sun_requirement": "full_sun",
        "spacing_cm": 5,
        "soil_mix": {"name": "Sandy Loam", "topsoil_pct": 60, "compost_pct": 20, "perlite_pct": 20, "description": "Light, well-drained mix that allows roots to grow straight."},
        "companion_crops": ["Onion", "Lettuce", "Rosemary"],
        "avoid_crops": ["Dill", "Fennel"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000006",
        "name": "Lettuce",
        "latin_name": "Lactuca sativa",
        "category": "vegetable",
        "description": "Cool-season leaf crop that bolts in heat. Cut-and-come-again varieties extend the harvest window.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Lettuce",
        "days_to_germination": 5,
        "days_to_harvest": 45,
        "watering_frequency_days": 1,
        "fertilise_frequency_days": 21,
        "prune_frequency_days": None,
        "prune_start_day": None,
        "sun_requirement": "partial_shade",
        "spacing_cm": 25,
        "soil_mix": {"name": "Light Mix", "topsoil_pct": 40, "compost_pct": 45, "perlite_pct": 15, "description": "Moisture-retentive yet airy mix for shallow-rooted crops."},
        "companion_crops": ["Carrot", "Radish", "Strawberry"],
        "avoid_crops": ["Celery"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000007",
        "name": "Spinach",
        "latin_name": "Spinacia oleracea",
        "category": "vegetable",
        "description": "Fast-maturing leafy green, ideal for successive sowing every 2–3 weeks. Bolts quickly in summer.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Spinach",
        "days_to_germination": 7,
        "days_to_harvest": 40,
        "watering_frequency_days": 2,
        "fertilise_frequency_days": 21,
        "prune_frequency_days": None,
        "prune_start_day": None,
        "sun_requirement": "partial_shade",
        "spacing_cm": 15,
        "soil_mix": {"name": "Light Mix", "topsoil_pct": 40, "compost_pct": 45, "perlite_pct": 15, "description": "Moisture-retentive yet airy mix for shallow-rooted crops."},
        "companion_crops": ["Strawberry", "Garlic"],
        "avoid_crops": ["Potato"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000008",
        "name": "Bell Pepper",
        "latin_name": "Capsicum annuum",
        "category": "vegetable",
        "description": "Long-season fruiting crop requiring warm temperatures. Pinching early growth encourages bushier plants.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Bell+Pepper",
        "days_to_germination": 10,
        "days_to_harvest": 80,
        "watering_frequency_days": 2,
        "fertilise_frequency_days": 14,
        "prune_frequency_days": 14,
        "prune_start_day": 30,
        "sun_requirement": "full_sun",
        "spacing_cm": 45,
        "soil_mix": {"name": "Tomato Mix", "topsoil_pct": 40, "compost_pct": 40, "perlite_pct": 20, "description": "Rich, well-draining mix that retains moisture while preventing root rot."},
        "companion_crops": ["Basil", "Carrot"],
        "avoid_crops": ["Fennel"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000009",
        "name": "Green Bean",
        "latin_name": "Phaseolus vulgaris",
        "category": "vegetable",
        "description": "Bush or climbing bean with high yield. Fixes nitrogen, improving soil for subsequent crops.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Green+Bean",
        "days_to_germination": 7,
        "days_to_harvest": 60,
        "watering_frequency_days": 2,
        "fertilise_frequency_days": 28,
        "prune_frequency_days": None,
        "prune_start_day": None,
        "sun_requirement": "full_sun",
        "spacing_cm": 10,
        "soil_mix": {"name": "Rich Bed Mix", "topsoil_pct": 50, "compost_pct": 40, "perlite_pct": 10, "description": "Nutrient-dense mix for heavy feeders."},
        "companion_crops": ["Carrot", "Cauliflower"],
        "avoid_crops": ["Onion", "Fennel"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000010",
        "name": "Radish",
        "latin_name": "Raphanus sativus",
        "category": "vegetable",
        "description": "One of the fastest crops from seed to harvest. Excellent as a gap-filler between slower crops.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Radish",
        "days_to_germination": 3,
        "days_to_harvest": 25,
        "watering_frequency_days": 1,
        "fertilise_frequency_days": 28,
        "prune_frequency_days": None,
        "prune_start_day": None,
        "sun_requirement": "partial_shade",
        "spacing_cm": 5,
        "soil_mix": {"name": "Sandy Loam", "topsoil_pct": 60, "compost_pct": 20, "perlite_pct": 20, "description": "Light, well-drained mix that allows roots to grow straight."},
        "companion_crops": ["Carrot", "Cucumber", "Lettuce"],
        "avoid_crops": [],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000011",
        "name": "Kale",
        "latin_name": "Brassica oleracea var. sabellica",
        "category": "vegetable",
        "description": "Hardy brassica that improves in flavour after frost. Harvest outer leaves to keep the plant productive.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Kale",
        "days_to_germination": 7,
        "days_to_harvest": 60,
        "watering_frequency_days": 2,
        "fertilise_frequency_days": 21,
        "prune_frequency_days": None,
        "prune_start_day": None,
        "sun_requirement": "full_sun",
        "spacing_cm": 45,
        "soil_mix": {"name": "Rich Bed Mix", "topsoil_pct": 50, "compost_pct": 40, "perlite_pct": 10, "description": "Nutrient-dense mix for heavy feeders."},
        "companion_crops": ["Beet", "Celery"],
        "avoid_crops": ["Tomato", "Strawberry"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000012",
        "name": "Garlic",
        "latin_name": "Allium sativum",
        "category": "vegetable",
        "description": "Long-season allium planted in autumn for summer harvest. A natural pest deterrent across the garden.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Garlic",
        "days_to_germination": 14,
        "days_to_harvest": 240,
        "watering_frequency_days": 7,
        "fertilise_frequency_days": 30,
        "prune_frequency_days": None,
        "prune_start_day": None,
        "sun_requirement": "full_sun",
        "spacing_cm": 15,
        "soil_mix": {"name": "Sandy Loam", "topsoil_pct": 60, "compost_pct": 20, "perlite_pct": 20, "description": "Light, well-drained mix that allows roots to grow straight."},
        "companion_crops": ["Carrot", "Tomato"],
        "avoid_crops": ["Bean", "Pea"],
        "created_at": now,
        "updated_at": now,
    },
    # ── Herbs ─────────────────────────────────────────────────────────────────
    {
        "id": "c1000000-0000-0000-0000-000000000013",
        "name": "Basil",
        "latin_name": "Ocimum basilicum",
        "category": "herb",
        "description": "Aromatic annual that thrives in heat. Pinch flower buds to extend leaf production and prevent bolting.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Basil",
        "days_to_germination": 7,
        "days_to_harvest": 30,
        "watering_frequency_days": 1,
        "fertilise_frequency_days": 21,
        "prune_frequency_days": 7,
        "prune_start_day": 21,
        "sun_requirement": "full_sun",
        "spacing_cm": 20,
        "soil_mix": {"name": "Herb Mix", "topsoil_pct": 30, "compost_pct": 50, "perlite_pct": 20, "description": "Rich and free-draining for herbs that need consistent moisture without waterlogging."},
        "companion_crops": ["Tomato", "Bell Pepper"],
        "avoid_crops": ["Sage", "Thyme"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000014",
        "name": "Mint",
        "latin_name": "Mentha spicata",
        "category": "herb",
        "description": "Vigorous perennial best grown in containers to contain its spreading roots. Repels aphids and ants.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Mint",
        "days_to_germination": 10,
        "days_to_harvest": 30,
        "watering_frequency_days": 1,
        "fertilise_frequency_days": 28,
        "prune_frequency_days": 14,
        "prune_start_day": 14,
        "sun_requirement": "partial_shade",
        "spacing_cm": 30,
        "soil_mix": {"name": "Herb Mix", "topsoil_pct": 30, "compost_pct": 50, "perlite_pct": 20, "description": "Rich and free-draining for herbs that need consistent moisture without waterlogging."},
        "companion_crops": ["Tomato", "Cabbage"],
        "avoid_crops": ["Parsley"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000015",
        "name": "Rosemary",
        "latin_name": "Salvia rosmarinus",
        "category": "herb",
        "description": "Drought-tolerant Mediterranean shrub. Thrives in poor, well-drained soil — overwatering is the main risk.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Rosemary",
        "days_to_germination": 14,
        "days_to_harvest": 90,
        "watering_frequency_days": 7,
        "fertilise_frequency_days": 60,
        "prune_frequency_days": 30,
        "prune_start_day": 60,
        "sun_requirement": "full_sun",
        "spacing_cm": 60,
        "soil_mix": {"name": "Mediterranean Mix", "topsoil_pct": 40, "compost_pct": 20, "perlite_pct": 40, "description": "Lean, gritty mix that mimics the rocky soils of the Mediterranean coast."},
        "companion_crops": ["Carrot", "Bean", "Cabbage"],
        "avoid_crops": ["Cucumber"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000016",
        "name": "Thyme",
        "latin_name": "Thymus vulgaris",
        "category": "herb",
        "description": "Hardy perennial with woody stems. Low maintenance once established — drought-tolerant and pest-resistant.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Thyme",
        "days_to_germination": 14,
        "days_to_harvest": 75,
        "watering_frequency_days": 5,
        "fertilise_frequency_days": 60,
        "prune_frequency_days": 21,
        "prune_start_day": 60,
        "sun_requirement": "full_sun",
        "spacing_cm": 30,
        "soil_mix": {"name": "Mediterranean Mix", "topsoil_pct": 40, "compost_pct": 20, "perlite_pct": 40, "description": "Lean, gritty mix that mimics the rocky soils of the Mediterranean coast."},
        "companion_crops": ["Strawberry", "Tomato"],
        "avoid_crops": ["Basil"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000017",
        "name": "Parsley",
        "latin_name": "Petroselinum crispum",
        "category": "herb",
        "description": "Biennial grown as an annual. Slow to germinate — soak seeds overnight to improve germination rate.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Parsley",
        "days_to_germination": 21,
        "days_to_harvest": 70,
        "watering_frequency_days": 2,
        "fertilise_frequency_days": 28,
        "prune_frequency_days": 14,
        "prune_start_day": 50,
        "sun_requirement": "partial_shade",
        "spacing_cm": 15,
        "soil_mix": {"name": "Herb Mix", "topsoil_pct": 30, "compost_pct": 50, "perlite_pct": 20, "description": "Rich and free-draining for herbs that need consistent moisture without waterlogging."},
        "companion_crops": ["Asparagus", "Carrot", "Tomato"],
        "avoid_crops": ["Mint", "Onion"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000018",
        "name": "Chives",
        "latin_name": "Allium schoenoprasum",
        "category": "herb",
        "description": "Hardy perennial allium. Cut to 5 cm above soil to encourage regrowth. Edible purple flowers attract pollinators.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Chives",
        "days_to_germination": 10,
        "days_to_harvest": 60,
        "watering_frequency_days": 2,
        "fertilise_frequency_days": 28,
        "prune_frequency_days": 21,
        "prune_start_day": 21,
        "sun_requirement": "full_sun",
        "spacing_cm": 15,
        "soil_mix": {"name": "Herb Mix", "topsoil_pct": 30, "compost_pct": 50, "perlite_pct": 20, "description": "Rich and free-draining for herbs that need consistent moisture without waterlogging."},
        "companion_crops": ["Carrot", "Tomato"],
        "avoid_crops": ["Bean", "Pea"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000019",
        "name": "Dill",
        "latin_name": "Anethum graveolens",
        "category": "herb",
        "description": "Feathery annual with culinary and ornamental value. Self-seeds readily — allow a few plants to flower.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Dill",
        "days_to_germination": 7,
        "days_to_harvest": 45,
        "watering_frequency_days": 2,
        "fertilise_frequency_days": 28,
        "prune_frequency_days": None,
        "prune_start_day": None,
        "sun_requirement": "full_sun",
        "spacing_cm": 30,
        "soil_mix": {"name": "Light Mix", "topsoil_pct": 40, "compost_pct": 45, "perlite_pct": 15, "description": "Moisture-retentive yet airy mix for shallow-rooted crops."},
        "companion_crops": ["Cucumber", "Onion"],
        "avoid_crops": ["Tomato", "Carrot", "Fennel"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000020",
        "name": "Coriander",
        "latin_name": "Coriandrum sativum",
        "category": "herb",
        "description": "Cool-season herb that bolts quickly in heat. Sow in succession every 3 weeks. Both leaves and seeds are edible.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Coriander",
        "days_to_germination": 7,
        "days_to_harvest": 35,
        "watering_frequency_days": 1,
        "fertilise_frequency_days": 28,
        "prune_frequency_days": 7,
        "prune_start_day": 21,
        "sun_requirement": "partial_shade",
        "spacing_cm": 20,
        "soil_mix": {"name": "Light Mix", "topsoil_pct": 40, "compost_pct": 45, "perlite_pct": 15, "description": "Moisture-retentive yet airy mix for shallow-rooted crops."},
        "companion_crops": ["Anise", "Carrot"],
        "avoid_crops": ["Fennel"],
        "created_at": now,
        "updated_at": now,
    },
    # ── Fruit ─────────────────────────────────────────────────────────────────
    {
        "id": "c1000000-0000-0000-0000-000000000021",
        "name": "Strawberry",
        "latin_name": "Fragaria × ananassa",
        "category": "fruit",
        "description": "Perennial fruiting plant producing runners. Remove runners to focus energy into fruit production.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Strawberry",
        "days_to_germination": 14,
        "days_to_harvest": 90,
        "watering_frequency_days": 2,
        "fertilise_frequency_days": 14,
        "prune_frequency_days": 30,
        "prune_start_day": 30,
        "sun_requirement": "full_sun",
        "spacing_cm": 30,
        "soil_mix": {"name": "Tomato Mix", "topsoil_pct": 40, "compost_pct": 40, "perlite_pct": 20, "description": "Rich, well-draining mix that retains moisture while preventing root rot."},
        "companion_crops": ["Lettuce", "Spinach", "Thyme"],
        "avoid_crops": ["Brassicas", "Fennel"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000022",
        "name": "Chilli Pepper",
        "latin_name": "Capsicum frutescens",
        "category": "fruit",
        "description": "Hot fruiting pepper requiring a long, warm growing season. Riper fruit = higher heat. Dries well for storage.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Chilli+Pepper",
        "days_to_germination": 10,
        "days_to_harvest": 90,
        "watering_frequency_days": 2,
        "fertilise_frequency_days": 14,
        "prune_frequency_days": 14,
        "prune_start_day": 30,
        "sun_requirement": "full_sun",
        "spacing_cm": 45,
        "soil_mix": {"name": "Tomato Mix", "topsoil_pct": 40, "compost_pct": 40, "perlite_pct": 20, "description": "Rich, well-draining mix that retains moisture while preventing root rot."},
        "companion_crops": ["Basil", "Carrot"],
        "avoid_crops": ["Fennel"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000023",
        "name": "Pumpkin",
        "latin_name": "Cucurbita maxima",
        "category": "fruit",
        "description": "Space-hungry vining crop. Best grown on the ground with trailing stems guided away from other plants.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Pumpkin",
        "days_to_germination": 7,
        "days_to_harvest": 110,
        "watering_frequency_days": 3,
        "fertilise_frequency_days": 21,
        "prune_frequency_days": None,
        "prune_start_day": None,
        "sun_requirement": "full_sun",
        "spacing_cm": 120,
        "soil_mix": {"name": "Rich Bed Mix", "topsoil_pct": 50, "compost_pct": 40, "perlite_pct": 10, "description": "Nutrient-dense mix for heavy feeders."},
        "companion_crops": ["Corn", "Bean"],
        "avoid_crops": ["Potato"],
        "created_at": now,
        "updated_at": now,
    },
    # ── Flowers ───────────────────────────────────────────────────────────────
    {
        "id": "c1000000-0000-0000-0000-000000000024",
        "name": "Marigold",
        "latin_name": "Tagetes erecta",
        "category": "flower",
        "description": "Hardy annual with strong pest-deterrent properties. Plant near tomatoes and peppers to repel nematodes and aphids.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Marigold",
        "days_to_germination": 5,
        "days_to_harvest": 60,
        "watering_frequency_days": 2,
        "fertilise_frequency_days": 28,
        "prune_frequency_days": 14,
        "prune_start_day": 30,
        "sun_requirement": "full_sun",
        "spacing_cm": 25,
        "soil_mix": {"name": "Light Mix", "topsoil_pct": 40, "compost_pct": 45, "perlite_pct": 15, "description": "Moisture-retentive yet airy mix for shallow-rooted crops."},
        "companion_crops": ["Tomato", "Bell Pepper", "Cucumber"],
        "avoid_crops": ["Bean"],
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "c1000000-0000-0000-0000-000000000025",
        "name": "Nasturtium",
        "latin_name": "Tropaeolum majus",
        "category": "flower",
        "description": "Edible flower and foliage. Thrives in poor soil — overfeeding produces leaves at the expense of flowers. Attracts aphids away from vegetables.",
        "thumbnail_url": "https://placehold.co/400x300/163526/ffffff?text=Nasturtium",
        "days_to_germination": 7,
        "days_to_harvest": 55,
        "watering_frequency_days": 3,
        "fertilise_frequency_days": 42,
        "prune_frequency_days": None,
        "prune_start_day": None,
        "sun_requirement": "full_sun",
        "spacing_cm": 30,
        "soil_mix": {"name": "Sandy Loam", "topsoil_pct": 60, "compost_pct": 20, "perlite_pct": 20, "description": "Light, well-drained mix that allows roots to grow straight."},
        "companion_crops": ["Courgette", "Cucumber"],
        "avoid_crops": [],
        "created_at": now,
        "updated_at": now,
    },
]


def upgrade() -> None:
    crops_table = sa.table(
        "crops",
        sa.column("id", sa.String),
        sa.column("name", sa.String),
        sa.column("latin_name", sa.String),
        sa.column("category", PgEnum("vegetable", "herb", "fruit", "flower", name="crop_category", create_type=False)),
        sa.column("description", sa.Text),
        sa.column("thumbnail_url", sa.String),
        sa.column("days_to_germination", sa.Integer),
        sa.column("days_to_harvest", sa.Integer),
        sa.column("watering_frequency_days", sa.Integer),
        sa.column("fertilise_frequency_days", sa.Integer),
        sa.column("prune_frequency_days", sa.Integer),
        sa.column("prune_start_day", sa.Integer),
        sa.column("sun_requirement", PgEnum("full_sun", "partial_shade", "shade", name="sun_requirement", create_type=False)),
        sa.column("spacing_cm", sa.Integer),
        sa.column("soil_mix", JSONB),
        sa.column("companion_crops", sa.ARRAY(sa.String)),
        sa.column("avoid_crops", sa.ARRAY(sa.String)),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(crops_table, CROPS)


def downgrade() -> None:
    op.execute("DELETE FROM crops")
