"""add_specimens_table

Revision ID: ba1e0e4bcc11
Revises: c3d4e5f6a7b8
Create Date: 2026-04-01 13:50:27.501435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ba1e0e4bcc11'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specimens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plot_slot_id', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('stage_override', sa.String(length=50), nullable=True),
    sa.Column('photo_log', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('milestones', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plot_slot_id'], ['plot_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plot_slot_id', name='uq_specimen_plot_slot')
    )
    op.create_index(op.f('ix_specimens_plot_slot_id'), 'specimens', ['plot_slot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_specimens_plot_slot_id'), table_name='specimens')
    op.drop_table('specimens')
    # ### end Alembic commands ###
